### ISSUE TITLE
Speakers

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#100]
Contactar y concretar charla con los speakers.
Agendar la charla en meetup.com

**Comment by mafesernaarboleda** [comment]
Yo puedo ayudar con esta 👍

**Comment by RamirezAlex** [comment]
@mafesernaarboleda tienes algunos posibles speakers? de los dos que teníamos pendientes ya uno dijo que no podía esta vez y el otro aun no me contesta. :(
cc @jessecogollo @edsadr @khriztianmoreno @CodeMaxter

**Comment by mafesernaarboleda** [comment]
Hola @ramirezAlex, ya me pongo en la tarea de buscar, deberíamos organizar un plan de contingencia para estos casos.

**Comment by JenyMzo** [comment]
Puedo ayudar acá también. @JenyMzo

**Comment by khriztianmoreno** [comment]
Me asigno esta tarea para enviar email ya mismo

**Comment by mafesernaarboleda** [comment]
Buenas!!
Los chicos respondieron o es necesario buscar speakers?

**Comment by khriztianmoreno** [comment]
@mafesernaarboleda aun no responden, tenemos en lista de espero otros dos personajes, pero se puede ir haciendo gestion con mas candidatos y que la registren en el [formulario](http://medellinjs.org/comparte).

**Comment by RamirezAlex** [comment]
No ha habido respuesta hasta ahora.

**Comment by khriztianmoreno** [comment]
Tomo esta tarea que ya tenia iniciada previamente desde la semana pasada.

**Comment by mafesernaarboleda** [comment]
Yo puedo ayudar acá!! 🙇🏻‍♀️

**Comment by JenyMzo** [comment]
@JenyMzo Yo también puedo ayudar
