### ISSUE TITLE
Social media

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#101]
Transmitir, grabar charla. Ademas tomar fotos y compartirla en sociales (facebook, twitter, instagram).

**Comment by pablovem** [comment]
🖐  Desconozco las artes óscuras de audio/video para hacer un buen streaming, pero puedo colaborar con las fotos. @pablovem

**Comment by JenyMzo** [comment]
Yo también puedo ayudar con esta tarea :)

**Comment by khriztianmoreno** [comment]
Yo me encargo del social media como se viene haciendo ultimamte y chevere que alguien de anime con el streaming

**Comment by juanarbol** [comment]
Yo podría ayudar con fotografías!

**Comment by camilomontoyau** [comment]
Considero que es mejor grabarlas que hacer streaming en directo, yo me puedo encargar de grabarlas
@camilomontoyau

**Comment by khriztianmoreno** [comment]
@camilomontoyau a mi me gusta esta idea tambien, tienes alguna idea de como grabarla que necesitariamos? Anteriormente veniamos usando [OBS](https://obsproject.com/) para capturar la pantalla del speaker, yo tengo ganas de poder lograr capturar ambas cosas pantalla y al speaker mientras habla, si tienes alguna idea la trabajamos.

Me cuentas, saludos.

**Comment by CodeMaxter** [comment]
Me parece que el hacer streaming es altamente problemático, por el tema del internet de Ruta N (o del lugar donde se realicen las charlas/talleres), que no siempre funciona a la mejor velocidad para ello, así que creo que lo mejor es grabar las charlas y publicarlas luego.

**Comment by camilomontoyau** [comment]
@khriztianmoreno OBS está bien para la captura de Pantalla y para grabar al speaker ponemos otro portátil en la mesa al lado y también tengo una go pro hero para que grabemos desde otro ángulo, de hecho si alguien más tiene cámara podemos hacer tomas de varios ángulos

**Comment by camilomontoyau** [comment]
@CodeMaxter si es por ese motivo que pienso que hacer streaming es un poco engorroso

**Comment by khriztianmoreno** [comment]
@camilomontoyau Hagamoslo asi con tu GoPro y vemos que debemos ir mejorando, que este sea el primer intento de algo bien interesante, si quiere charlamos el finde con una :beers: 

@pablovem @JenyMzo el tema de las fotos, videos, boomerangs etc etc, va a ser de la siguiente manera, ustedes capturan los momentos que crean son valiosos y me los van a ir compartiendo a mi por medio de whatsapp, slack etc, nos ponemos de acuerdo el dia del evento y yo me encargo de subirlos a las redes.

Me cuentan todos que opinan...

**Comment by camilomontoyau** [comment]
@khriztianmoreno de una!, el sábado estaré en NodoCoworking cómo mentor del workshop de React Medellín, si quiere nos encontramos por la tarde por los lados del parque del Poblado

**Comment by pablovem** [comment]
Listo @khriztianmoreno.

**Comment by camilomontoyau** [comment]
hola, yo vuelvo a ayudar con lo del video, lastimosamente salió mal hace un mes, pero cómo no daré charla puedo enfocarme solamente en esta tarea y tratar de hacerla mejor que la otra.

**Comment by khriztianmoreno** [comment]
@camilomontoyau parce excelente, esta vez que si nos va a quedar una elegancia y luego lo editamos con unos cursitos

**Comment by camilomontoyau** [comment]
@khriztianmoreno 
![](https://gifrific.com/wp-content/uploads/2012/08/Man-with-beard-approves.gif)

**Comment by camilomontoyau** [comment]
@khriztianmoreno no podré asistir este miércoles porque seré el mentor del día en CodeRise.
Ya revisaste los dos videos que te mandé del pasado meetup ?

**Comment by camilomontoyau** [comment]
@khriztianmoreno acabo de ver que no hicieron el meetup ayer, el próximo miércoles si puedo asistir

**Comment by khriztianmoreno** [comment]
@camilomontoyau ya vi los videos, quedaron una nota, pero sin audio jaja, lo segundo, yo este miercoles no podre estar entonces si algo te pido el favor te empoderes del video igual esperemos hasta el lunes que ha pasado para ver con quien mas contamos para hacer tood el tema de redes sociales.

**Comment by camilomontoyau** [comment]
@khriztianmoreno  los videos que te pasé están sin audio?
jajaja, ok voy a mirar qué pasó.
Dale si no podés estar yo tomo fotos y hago el video, no problem

**Comment by camilomontoyau** [comment]
@khriztianmoreno los acabo de descargar y si tienen audio, debe ser que no tienes el codec

**Comment by khriztianmoreno** [comment]
@camilomontoyau Voy a revisar descargandoos en otra maquina, de todas formas, que deberia instalar?
