### ISSUE TITLE
Host

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#102]
Es el responsable de hablar en la charla, presentar a los speakers, dar los avisos parroquiales.
Llegar de primero, para cuadrar todo con mauricio y hacerse cargo de los adaptadores y el microfono.
e irse de último.
Actualizar la presentación http://slides.com/medellinjs/medellinjs#/ por si falta algo.

**Comment by CodeMaxter** [comment]
@CodeMaxter
