### ISSUE TITLE
Propuesta de diseño

### ISSUE THREAD

**Issue by jupa8712** [coljs/medellinjs#105]
![01 home](https://user-images.githubusercontent.com/27877477/29831240-1a18e0d6-8caa-11e7-82e0-35161a81c4f6.png)
![02 acerca de](https://user-images.githubusercontent.com/27877477/29831242-1a1a6fb4-8caa-11e7-95fd-9cd430fbd6c7.png)
![03 eventos](https://user-images.githubusercontent.com/27877477/29831243-1a1c527a-8caa-11e7-8945-e5728e78b671.png)
![04 blog](https://user-images.githubusercontent.com/27877477/29831244-1a1cef3c-8caa-11e7-9e77-3ec4a42501ae.png)
![05 blog interna](https://user-images.githubusercontent.com/27877477/29831241-1a1947ce-8caa-11e7-8f19-89730f585bf8.png)
![06 charlas](https://user-images.githubusercontent.com/27877477/29831245-1a228762-8caa-11e7-8b29-337e1cfa2457.png)
![07 comparte](https://user-images.githubusercontent.com/27877477/29831247-1a69016a-8caa-11e7-8b3d-21b6e73709ef.png)
![menu](https://user-images.githubusercontent.com/27877477/29831246-1a640df4-8caa-11e7-9bd4-108d2ab6ce9c.jpg)

**Comment by jessecogollo** [comment]
Gracias @jupa8712

**Comment by jessecogollo** [comment]
Voluntarios, la idea de este ticket es pasar ese diseño a HTML/template para ser utilizando en la pagina de medellinjs.org.

**Comment by pablovem** [comment]
✋

**Comment by JenyMzo** [comment]
Yo le ayudo a @pablovem

**Comment by edsadr** [comment]
🙏🏾

**Comment by pablovem** [comment]
La propuesta actual consiste en utilizar Vue.js y aprovechar Medium para el tema de las entradas del blog.

**Comment by khriztianmoreno** [comment]
@pablovem Justo estoy terminando un proyecto con Nuxt.js que tiene un sitio web y crea los post directamente a medium desde el sitio utilizando el SDK para NodeJS de Medium.com Espero poder tener un coco libre estos dias para compartirlo y ver que les puede servir.
