### ISSUE TITLE
Sistema de Puntuacion

### ISSUE THREAD

**Issue by khriztianmoreno** [coljs/medellinjs#107]
Este es una guia rapida de evaluacion de puntos que mide la participacion de todos los `co-orgnizadores` y `colaboradores`.

*Esta tabla de valores aplica unicamente para `co-orgnizadores` y `colaboradores`*

## Evaluacion General:
- Asistencia Charlas: `1 punto`
- Asistencia a Talleres: `1 punto`
- Speaker Charla:  `2 punto` *gana camisa de medellinjs (de no tenerla)*
- Speaker Taller: `2 punto` *gana camisa de medellinjs (de no tenerla)*

## Evaluacion Especifica: 
- Host, responsable de presentar evento: `1 punto`
- Contacto speakers:
  - Enviar Email: `1 punto`
  - 911, conseguir otro: `1 punto`
- Social Media:
  - Tweets publicados: `1 punto`
  - Post en Facebook publicados: `1 punto`
  - Participacion en la grabacion, edicion y publiacion del video del meetup `1 punto`
- Comida:
  - Llamar al proveedor: `1 punto`
  - Recoger producto en evento: `1 punto`
  - Servir y organizar mesas antes y despues de la comida `1 punto`

## Evaluacion Otros: 
- Conseguir Patrocinador: `2 punto`
- WebSite MedellinJS: `1 punto`
- PullRequest resueltos: `1 punto`

Con estos apsectos a evaluar, **cada 3 meses** se realizará una tabla de clasificacion donde evidenciaremos el trabajo realizado por los `co-orgnizadores` y `colaboradores` con el fin de indentificar la persona que puede salir de los `co-orgnizadores` y cual de los `colaboradores` entraria a formar parte de los **co-orgnizadores oficiales de MedellinJS**

### Ejemplo

|                        | Brendan Eich | David Heinemeier | Guido van Rossum |
|------------------------|--------------|------------------|------------------|
| Speaker Charla         |       2      |         2        |         0        |
| Speaker Taller         |       2      |         0        |         2        |
| Asistencia Charlas     |       1      |         1        |         1        |
| Asistencia Talleres    |       1      |         0        |         0        |
| Host Evento            |       0      |         1        |         1        |
| Contacto Speaker Email |       1      |         1        |         1        |
| Contacto Otro Speaker  |       1      |         1        |         1        |
| Tweets publicados      |       4      |         2        |         1        |
| FB publicados          |       0      |         0        |         1        |
| Video Evento           |       1      |         1        |         0        |
| Provedor Comida        |       1      |         1        |         1        |
| Recoger Comida         |       0      |         1        |         2        |
| Servir Comida          |       3      |         2        |         0        |
| Conseguir Patrocinador |       2      |         0        |         0        |
| WebSite                |       1      |         0        |         0        |
| Github                 |       1      |         1        |         1        |
| **TOTAL**              |    **21**    |      **14**      |     **11**      |

### Obeservaciones:

- Una persona puede dar solo una charla y un taller en cada trimestre por lo tanto el maximo de puntos que puede tener en cada una de estas casillas es `2 puntos`
- Una pesona puede asistir a maximo 3 Charlas en cada trimestre, por lo tanto el maximo de puntos que puede tener en esta casilla es `3 puntos`
- Una pesona puede asistir a maximo 3 Talleres en cada trimestre, por lo tanto el maximo de puntos que puede tener en esta casilla es `3 puntos`
- El número maximo de Twetts y publicaciones en Facebook para ser tenidas en cuenta es 5, por lo tanto el maximo de puntos que puede tener en estas casillas es `5 puntos`
- En caso de que la persona de los `colaboradores` que mayor puntaje obtenga no supere al menor puntaje de los `co-organizadores` este no sera promovido.

**Comment by jessecogollo** [comment]
En este item, aparte de los dos puntos agregaria que se gana camisa de medellinjs (de no tenerla).
Speaker Charla: 2 punto
Speaker Taller: 2 punto

**Comment by jessecogollo** [comment]
Este item, especificar que es para voluntarios y co-organizadores
Asistencia Charlas: 1 punto
Asistencia a Talleres: 1 punto

**Comment by jessecogollo** [comment]
@pablovem  mira la información acá.

**Comment by jessecogollo** [comment]
https://docs.google.com/spreadsheets/d/1FjjYmwtdMpr0mFX1EliedTi8qdtgyviuUYEwUzOqZrA/edit?usp=sharing
