### ISSUE TITLE
agregar  sección para comunidades JS de medellin

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#132]

**Comment by Addin** [comment]
Este issue se puede marcar como solucionado, ya existe una sección de comunidades 👏

**Comment by jessecogollo** [comment]
Addin, es agregar las comunidades de javascript de medellín.

**Comment by Addin** [comment]
Cierto @jessecogollo, fue mi error, la pregunta es, fuera de MedellinJS, ¿Existen otras comunidades de JavaScript?

**Comment by michel1024** [comment]
@Erick Voy a estar trabajando en esto
