### ISSUE TITLE
Crear enlace medellinjs.org/sponsor

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#145]
Donde se visualize(descargue) el prospecto de sponsors

**Comment by Pabloqv10** [comment]
@pabloqv10 Asignar por favor

**Comment by Pabloqv10** [comment]
Voy a trabajar esto @pabloqv10

**Comment by Pabloqv10** [comment]
Que es lo que se debe descargar ?

**Comment by jessecogollo** [comment]
@Pabloqv10 este es el link https://drive.google.com/file/d/1AAFjSuUHwXvk_ObmMzIB98yRzPvMsLlN/view?usp=sharing
