### ISSUE TITLE
integrar archivo cuentas a la pagina

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#146]
https://docs.google.com/spreadsheets/d/1S5wKPlgxg-sDEyOQQr0NaxXwE4g3zg2oEUgxn_ylSmA/edit?usp=sharing

**Comment by Greshot** [comment]
¿En que sección/ubicación debería ir el vínculo al archivo de de cuentas?

**Comment by Greshot** [comment]
@jessecogollo Asignarme por favor

**Comment by jessecogollo** [comment]
@Greshot   puede ir en el nabvar y en el footer.
