### ISSUE TITLE
Relajar la configuración del linter

### ISSUE THREAD

**Issue by elyalvarado** [coljs/medellinjs#160]
El linter está en modo demasiado estricto y ocasiona errores de compilación por cuestiones de estilo. La recomendación es quitar chequeos de estilo del linter y en todo caso crear una configuración aparte para prettier.
Esto es especialmente importante para aquellos que tenemos configurado automáticamente en nuestros editores prettier al guardar archivos.

**Comment by elyalvarado** [comment]
Chicas y chicos @JenyMzo @mafesernaarboleda @jessecogollo @khriztianmoreno, les tengo una pregunta con respecto a este issue:

Actualmente la configuración de nuxt está de forma que cada vez que webpack genere el proyecto (en cada save) se corre el linter, y esto ,aunado a que eslint está verificando los estilos, es lo que reporté en este issue, porque en mi caso al menos la experiencia de desarrollo fue compleja al tener problemas de compilación a cada momento por reglas simples de estilo que no deberían impedir el avance, sino ser corregidas automáticamente (ej: dangling-comma, missing-semi-colon, etc...).

Lo que propongo es mantener la ejecución del linter en cada save, pero separar el chequeo de estilo del linter, y usar prettier. Se puede además configurar un precommit hook usando `lint-staged` y `husky` para asegurarnos que el código sea formateado automáticamente por `prettier` antes de cada commit. 

Me gustaría que me indicaran si están de acuerdo, o si tienen alguna otra sugerencia antes de ponerme a cambiar la configuración.

**Comment by JenyMzo** [comment]
@elyalvarado Muchas gracias por tu aporte, me parece muy buena idea implementar Prettier con husky y lint-staged para formatear el código antes de hacer commit. Teniendo en cuenta que son compatibles con Eslint, por mí está bien lo que sugieres. :blush:

**Comment by elyalvarado** [comment]
Es cierto lo que dices @khriztianmoreno, sin embargo considero que cuando alguien está aprendiendo un nuevo framework o lenguaje es preferible que se enfoque en lo esencial primero, y las reglas que dan errores por estilos pueden crear confusión. En este sentido la experiencia de aprendizaje se ve interrumpida por errores de estilo que no son esenciales, y que para los nuevos programadores pueden ser confusos, al no poder distinguirlos tal vez de errores de sintaxis.

Estos errores de estilo pueden resultar frustrantes para alguien que está aprendiendo. En mi caso, no conocía para nada Vue, y cada vez que creía que entendía algo me veía interrumpido por un error de estilo, que además no tenía nada que ver con no llevar un estándar limpio y práctico, sino a utilizar uno distinto al usado en el proyecto.

Adicionalmente, cada vez más hay más y mejores herramientas para adherirse a estándares de formato de código automáticamente, y creo que con este proyecto tenemos una oportunidad importante de enseñar a la comunidad a usar estás herramientas. 

Estas herramientas además son una increíble fuente de aprendizaje sobre mejores prácticas, yo por ejemplo lo tengo configurado para formatearlo cada vez que hago save, y cuando veo que hace un cambio siempre tengo un momento "ajá", y aprendo algo.

Creo que a lo mejor podemos cumplir ambos cometidos, y propongo lo siguiente:

- Eliminar las reglas de estilo de `eslint`.
- Explicar en el Readme (o añadir un link a un MD adicional en el repo) cuales son las convenciones de estilo de código, y como se puede usar `prettier` para automatizarlas, y escribir un artículo en medium sobre como configurarlo automáticamente en los editores más usados: vscode, atom, sublime.
- Agregar el precommit hook que ejecute `prettier`, pero en lugar de hacer la corrección automática, indique los errores y muestre un link al artículo señalado anteriormente.

**Comment by khriztianmoreno** [comment]
@elyalvarado te compro la idea del `precommit` hook y de que se debe definir en el `README` cuales son las convenciones que se deben seguir, pero sigue sin gustarme eliminar las reglas de estilo de eslint.
