### ISSUE TITLE
integrar google analitycs

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#174]

**Comment by di3cruz** [comment]
Hola, Que cuenta de google analitycs desean integrar ?

**Comment by jessecogollo** [comment]
Hola @di3cruz 
`
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-118815653-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-118815653-1');
</script>
`

**Comment by khriztianmoreno** [comment]
https://nuxtjs.org/faq/google-analytics#how-to-use-google-analytics-

**Comment by di3cruz** [comment]
Perfecto, Esta semana trabajare en este tema.
