### ISSUE TITLE
The Protocol-relative URL

### ISSUE THREAD

**Issue by khriztianmoreno** [coljs/medellinjs#184]
Paul Irish escribió sobre la URL relativa al protocolo allá por 2010. Fue una pequeña publicación conveniente que aconsejaba a los desarrolladores abandonar los esquemas URL de protocolo absoluto usando `http://` o `https://` a favor de una variante relativa al protocolo que se ve como algo como esto: 

`<img src="//domain.com/img/logo.png">`

La invitación es cambiar todos los _http_ o _https_ que tengamos en el codigo por un *protocolo relativo*

**Comment by alejandr0pg** [comment]
@alejandr0pg

**Comment by Addin** [comment]
Me puse a investigar sobre eso que comentas, la publicación es esta [https://www.paulirish.com/2010/the-protocol-relative-url/](url) pero él dice que ahora es un anti-pattern.
