### ISSUE TITLE
las cajas de eventos tienen altura de diferente tamaño.

### ISSUE THREAD

**Issue by CMOW5** [coljs/medellinjs#191]
Sería bueno poner el mismo tamaño en las cajas de eventos para que la página se vea más bonita.
también está un poco relacionado con este issue  #156 . Yo podría intentar solucionarlos.

![medjs](https://user-images.githubusercontent.com/25666614/41185850-7aa2e046-6b52-11e8-9bd9-e45723a8a784.png)

**Comment by HugoLaguna** [comment]
Hola, 
quiero resolver el problema

**Comment by CMOW5** [comment]
@HugoLaguna yo hace un tiempo le empecé a trabajar y acabo de crear un pull request. Si quiere le haces un review porque pues yo no soy muy teso en css que digamos  :sweat_smile: pero la idea es aprender :smiley:
