### ISSUE TITLE
crear pagina medellinjs.org/campusjs

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#197]
En esta pagina existira un formulario, para que las universidades se postulen y medellinjs haga un campusjs en la universidad postulada.

**Comment by di3cruz** [comment]
Me puedes suministrar por favor el link del formulario de google ?

**Comment by Addin** [comment]
No sé en qué quedó esto, @jessecogollo @di3cruz  ⬆️

**Comment by jessecogollo** [comment]
Creo que no se va a implementar... a no ser que los organizadores lo tengan en el radar. y se puede implementar.
