### ISSUE TITLE
agregar prospecto sponsonrs ingles https://medellinjs.org/sponsor-en/

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#203]
Agregar PDF para sponsors en ingles tal como esta https://medellinjs.org/sponsor
link PDF: https://drive.google.com/file/d/1l5k8R7wUefFksHmKctTBGuV-dZFmcUg-/view?usp=sharing

y agregar la pregunta en ingles que redireccione al PDF 
`Quieres ser patrocinador?`

**Comment by HugoLaguna** [comment]
puede hacer este ?

**Comment by jessecogollo** [comment]
Claro que si Hugo

**Comment by jessecogollo** [comment]
merged
