### ISSUE TITLE
Agregar información speaker/charla [Workshop] React 101

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#204]
Juan David, Por favor actualizar la sección de heroes de la pagina web de medellinjs con la información relacionada con su taller https://github.com/coljs/medellinjs/blob/master/assets/data/heroes.js

**Comment by juandatoro** [comment]
Hola  

En el siguiente link pueden ver el repositorio en donde se encuentra el código que trabajamos [https://github.com/juandatoro/react101](url)

**Comment by jessecogollo** [comment]
Hola Juan, la idea es que actualices este archivo https://github.com/coljs/medellinjs/blob/master/assets/data/heroes.js
Con los datos tuyos, para que salgas en la pagina de medellinjs
Este es un ejemplo 
`humobinario: {
    name: 'Andrés Ossa Arango',
    username: 'HumoBinario',
    twitter: 'https://twitter.com/HumoBinario',
    github: '',
    avatar: 'https://pbs.twimg.com/profile_images/938595601444253696/ltvu-Bws_400x400.jpg',
    slides: [
      {
        direction: 'r',
        title: 'Code & Art',
        url: '',
        thumbnail: ''
      }
    ]
}`

**Comment by jessecogollo** [comment]
@juandatoro :arrow_up: :wink:

**Comment by Addin** [comment]
Este issue se puede marcar como solucionado, @juandatoro ya aparece como héroe 😎 

<img width="178" alt="capture" src="https://user-images.githubusercontent.com/6179522/52440984-7d574d80-2aed-11e9-929d-94fc86e05937.PNG">
