### ISSUE TITLE
cambiar los contrastes de color

### ISSUE THREAD

**Issue by gomezjuliana** [coljs/medellinjs#207]
Los sugientes textos no tienen el contraste lo suficientemente alto:

## Header:

El texto de los parafos (#FFFFFF sobre #1C7FB4)

## Proximos eventos:

El texto del titulo y de la description (#f5f5f5 sobre #48A8DD)
El texto de description de eventos pasados (#FFFFFF sobre #1183BE) 
El titulo del proximo meetup (#1293d5 sobre #E2E3E3)
La descripcion del proximo meetup (#1293d5 sobre #FFFFFF)

## Heros:
El subtitulo de la section (#818181 sobre #FFFFFF)

## Somos MedellinJS & Sponsors
El titulo (#F5F5F5 sobre #48A8DD)
El subtitulo (#f3f3f3 sobre #48A8DD)
Los titulos de los meetups (#F5F5F5 sobre #48A8DD)
Los titulos de los sponsors (#FFFFFF sobre #48A8DD)

## Imparte una charla:
el texto (#818181 sobre #FFFFFF)

## Organizadores:
los nombres (#1193d4 sobre #F5F5F5)

## footer:
el copyright (#FFFFFF sobre #48A8DD)

**Comment by Addin** [comment]
Este issue se puede marcar como solucionado, los cambios ya están aplicados en la página.

**Comment by IvanDev85** [comment]
@alerodrigueze
