### ISSUE TITLE
Sugerencia: Actualizaciòn de la portada de la pagina

### ISSUE THREAD

**Issue by HugoLaguna** [coljs/medellinjs#210]
Hola a todos 
Me gustaría sugerir un cambio en la portada de la pagina un poco mas visual.

![portada](https://user-images.githubusercontent.com/33559104/43415851-44da7a8c-93fc-11e8-8092-e39feef2e9cc.JPG)

**Comment by jessecogollo** [comment]
Hola @HugoLaguna, esta genial. Lo uunico, es que por favor no le cambies la tipografia a donde dice `Medellin JS` de resto esta espectacular.

**Comment by HugoLaguna** [comment]
OK entonces asi
![sdffd](https://user-images.githubusercontent.com/33559104/43427483-56bf3fbc-941f-11e8-8ee7-7827f93d0914.JPG)

**Comment by JenyMzo** [comment]
Hola @HugoLaguna Me parece que el fondo se ve mejor así, sin el background lleno de hexágonos, siento que ya es demasiado cargado, imagen, color y textura encima. 

![image](https://user-images.githubusercontent.com/2567952/43560419-f2a7e578-95d7-11e8-9817-d81255fceb73.png)

**Comment by HugoLaguna** [comment]
@JenyMzo si tenia mis dudas sobre esa textura, estoy de acuerdo voy hacer los cambios.

**Comment by jessecogollo** [comment]
merged
