### ISSUE TITLE
crear pagina http://medellinjs.org/fundacion/

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#213]
ejemplo: http://avanet.org/fundacion/

**¿Por qué una fundación?**
Hemos creado este grupo con el fin de reunir, compartir y aprender de los desarrolladores JavaScript de la ciudad de Medellín, Colombia.

Nuestra filosofía será siempre la de mantener un ambiente informal, nada estricto en ningún sentido. Así que cualquier colaboración, en cualquier sentido, será muy bien recibida.

**Documentos Públicos**
TBD

**Comment by JenyMzo** [comment]
@jessecogollo 

1. Cambiar el nombre de la carpeta "Fundation" por "Foundation" u "Organization"
2. Ubicar el link que lleva a la info de la fundación

**Comment by JenyMzo** [comment]
que no puedo verla info de la fundación el la página, en el código creaste en los componentes una página fundacion.vue y una  carpeta fundation y dentro tiene el index y los docs, pero no veo donde se linkea a esa página.

**Comment by jessecogollo** [comment]
ahhh ok, mira es siguiendo este link medellínjs.org/fundacion
En el index, donde me recomiendas colocarlo en el footer o en la cabecera?

**Comment by JenyMzo** [comment]
En el navbar

**Comment by jessecogollo** [comment]
merged medellinjs.org/fundacion
