### ISSUE TITLE
reducir espacio en la seccion de Heroes

### ISSUE THREAD

**Issue by HugoLaguna** [coljs/medellinjs#232]
me gustaria proponer algo para reducir el espacio que ocupa Heroes que, sobre todo el responsive, es muy largo, por un diseño como este
![captura de pantalla 2018-10-10 a la s 7 08 05 p m](https://user-images.githubusercontent.com/33559104/46772892-02f1fa80-ccc0-11e8-81ca-cd44ea0d4940.png)

**Comment by jessecogollo** [comment]
@HugoLaguna yo lo veo muy bonito, puedes mandar el PR?

**Comment by Addin** [comment]
Interesante la propuesta de @HugoLaguna , en espera de su pull request 😱

**Comment by silvermiguel96** [comment]
Tomare este @jessecogollo

**Comment by HugoLaguna** [comment]
Que pena que no pude terminarlo 😞se me complico demasiado con el responsive y no he tenido el tiempo.
