### ISSUE TITLE
Agregar Matter Sypply Co a la sección de sponsors

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#237]
Nombre: MATTER SUPPLY CO
imagen: https://s3.amazonaws.com/media-p.slid.es/uploads/245238/images/5118287/wordmark-cropped.png

**Comment by Addin** [comment]
Este Issue se puede marcar como solucionado, ya está agregado Matter Supply como sponsor en la página.

<img width="300" alt="capture" src="https://user-images.githubusercontent.com/6179522/52434393-32353e80-2add-11e9-99e2-2907834410db.PNG">
