### ISSUE TITLE
Agregar Colombia Dev a la sección de sponsors

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#238]
Nombre: COLOMBIA DEV
imagen: https://colombia-dev.org/public/assets/images/condor-logo.svg

**Comment by Addin** [comment]
Este Issue se puede marcar como solucionado, ya está agregado Colombia Dev como sponsor a la página.

<img width="300" alt="capture" src="https://user-images.githubusercontent.com/6179522/52434268-f0a49380-2adc-11e9-9554-bd8777708580.PNG">
