### ISSUE TITLE
agregar nodesource como sponsor de medellinjs

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#241]

**Comment by Angelfire** [comment]
@jessecogollo Para este issue necesitamos el logo de NodeSource que queremos usar.

**Comment by Addin** [comment]
Le hago UP a esto, ¿todavía siguen siendo Sponsor?

**Comment by cojimene** [comment]
@cojimene

**Comment by RafaelEduardoRodriguez** [comment]
Tomaré este issue @jessecogollo

**Comment by Addin** [comment]
Ya aparece NodeSource como patrocinador, podemos marcarlo como solucionado.

<img width="233" alt="Capture" src="https://user-images.githubusercontent.com/6179522/56602683-a56e2d00-65c3-11e9-9733-b1e434e6e119.PNG">
