### ISSUE TITLE
agregar a yungol a la seccion e sponsors

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#242]
Empresa de contabilidad que nos ayuda en este tema

**Comment by Angelfire** [comment]
Necesitamos el logo y la URL del proyecto/empresa.

**Comment by Addin** [comment]
Me parece que los datos son estos:

URL: [https://yungol.com/](url)
Logo: [https://imgur.com/X6dFjjm](url)

Si todavía siguen siendo Sponsor, informen para agregarlos a la página.

**Comment by Skouro** [comment]
tomare este @Skouro
