### ISSUE TITLE
Error ortográfico en el navbar

### ISSUE THREAD

**Issue by Addin** [coljs/medellinjs#253]
Hola, en el navbar en el último elemento tienen un error ortográfico, debería ser 
"Inscribe tu charla" omitiendo las mayúsculas iniciales después de "Inscribe".

<img width="200" alt="capture" src="https://user-images.githubusercontent.com/6179522/52355590-96360500-2a00-11e9-979e-543056353ad9.PNG">

**Comment by jessecogollo** [comment]
@Addin un PR seria bien chevere para arreglarlo :heart:

**Comment by Addin** [comment]
Hola @jessecogollo  Estoy tratando de corregirlo, pero cuando accedo al archivo AppNavBar.vue parece que está todo correcto.

<img width="800" alt="capture" src="https://user-images.githubusercontent.com/6179522/52366680-58dd7180-2a18-11e9-9d58-6027c5afb467.PNG">

**Comment by khriztianmoreno** [comment]
@Addin gracias por tu interes. Puedes corregirlo con eliminar la transformacion del texto en el css ` text-transform: capitalize;` 

Revisalo y me cuentas  👀

**Comment by Addin** [comment]
@khriztianmoreno Hecho, ahí envíe el PR, espero esté todo bien.
