### ISSUE TITLE
Sección Héroes con elemento no funcional

### ISSUE THREAD

**Issue by Addin** [coljs/medellinjs#255]
Hola, en la sección de Héroes, en donde se muestran las redes sociales hay un elemento extraño que ocasiona un bug.

<img width="150" alt="capture" src="https://user-images.githubusercontent.com/6179522/52356514-5c65fe00-2a02-11e9-86d1-2f0ced65def7.PNG">

Si se le da click, aparecen estos elementos:
<img width="520" alt="capture" src="https://user-images.githubusercontent.com/6179522/52356696-b23aa600-2a02-11e9-9b6a-bf51358a8e70.PNG">

**Comment by Addin** [comment]
Leyendo el código veo que ese botón despliega los slides del héroe, solo que los despliega de una forma un poco extraña, tal vez si se incrustan los slides en un modal la forma de mostrarlos seria mejor.

**Comment by JohanHiguita** [comment]
trabajaré en este issue @johanhiguita
