### ISSUE TITLE
Alinear footer en la sección de Héroes

### ISSUE THREAD

**Issue by Addin** [coljs/medellinjs#256]
Hola, en la sección de Héroes, el footer está centrado hacia arriba (tapando media cara del Héroe) sería bueno centrarlo hacia abajo.

<img width="141" alt="capture" src="https://user-images.githubusercontent.com/6179522/52356934-31c87500-2a03-11e9-8365-ff235a840cd4.PNG">

**Comment by d4vsanchez** [comment]
Tomo este issue @jessecogollo.

**Comment by JohanHiguita** [comment]
Voy a trabajar en este issue @johanhiguita
