### ISSUE TITLE
Algunos héroes no tienen imagen

### ISSUE THREAD

**Issue by Addin** [coljs/medellinjs#257]
Hola, en la sección de Héroes, hay algunos que no tienen imágenes.

<img width="186" alt="capture" src="https://user-images.githubusercontent.com/6179522/52357184-a9969f80-2a03-11e9-9b0a-3fc9b650c610.PNG">

Aquí la lista de los héroes que no tienen imágenes.

1.  Felipe Janer

2. Alexanda Vargas

3. Mateo Calle

4. Andrés Ossa Arango

**Comment by yhormanp** [comment]
tomaré este issue @yhormanp

**Comment by yhormanp** [comment]
también se encontro a estos sin imagen:

Samuel Burbano Ramos
Julián Gutiérrez
