### ISSUE TITLE
Sección de "Próximos eventos" muestra un evento ya realizado.

### ISSUE THREAD

**Issue by Addin** [coljs/medellinjs#262]
Hola, no sé si así esté programado o es un bug, pero en la sección de "Próximos eventos" ahora mismo está mostrando un evento que ya se realizó.

<img width="944" alt="capture" src="https://user-images.githubusercontent.com/6179522/52441964-0bccce80-2af0-11e9-8ac5-1b568c7aa151.PNG">

**Comment by jessecogollo** [comment]
Así es el feature, la cinta roja dice `pasó`.
