### ISSUE TITLE
Pagina de Heroes

### ISSUE THREAD

**Issue by khriztianmoreno** [coljs/medellinjs#267]
Crear una *pagina independiente* para los heroes, donde podamos ver en detalle en lista cada uno de los heroes de la comunidad.

## Motivación
Actualmente nuestro sitio cuenta con un diseño *One Page* lo que dificulta leer la pagina completamente. Se propone mejorar la lectura del siito reduciendo la seccion de **heroes** teniendo aleatoriamente algunos y un boton  debajo que permita navegar a otra pagina dodne pueda ver en detalle todos los demas heroes.

## Criterios de aceptacion
- [ ] Crear una nueva pagina `/heroes` donde se muestre todos los heroes actuales. *(Puede ser el mismo componente actual, pero dentro de una pagina independiente)*
- [ ] En la pagina de inicio modificar la seccion de **heroes**  para mostrar aleatoriamente 4, maximo 6 heroes. *(En este punto puede ser proactiv@)*
- [ ] Adicionar un boton de **Conoce todos nuestros heroes** debajo de la seccion *heroes* de la pagina de inicio. Este boton/enlace debe llevar a la pagina `/heroes`

Cualquier comentario o duda, puede dejarlo acá abajo.

**Comment by Addin** [comment]
Hola @khriztianmoreno me gusta la idea, tenía pensado abrir un issue similar, por la forma en que está diseñada la página, se puede reducir aún más su tamaño ya que hay algunos elementos que ocupan mucho espacio.

En esta imagen podemos ver que hay mucho espacio que no se utiliza entre el nombre de la comunidad "MedellínJS", el texto que describe a la comunidad y el cubo, con unos cambios en estos elementos se puede reducir el tamaño de la página, aunque de fondo está la imagen del auditorio.

<img width="950" alt="error 9" src="https://user-images.githubusercontent.com/6179522/52743466-14b61800-2fa8-11e9-8251-d5d4dcfaeca6.PNG">

En esta también podemos reducir el tamaño entre el título y los próximos eventos.

<img width="945" alt="error 10" src="https://user-images.githubusercontent.com/6179522/52744489-d2420a80-2faa-11e9-8e08-fe823b5ba045.PNG">

Y en esta entre el título y los organizadores se puede reducir el tamaño igual.

<img width="951" alt="error 11" src="https://user-images.githubusercontent.com/6179522/52744540-f867aa80-2faa-11e9-822b-0046f406f833.PNG">

**Comment by khriztianmoreno** [comment]
@Addin estoy de aceurdo contigo con referencia a los espacios, pero eso lo podemos manejar como otro issue, que sea algo como reducir espacios o aires en los contenidos. Para mantener este muy consiso.

**Comment by Addin** [comment]
@khriztianmoreno es cierto, voy a abrir un issue para reportar eso, disculpa por desvirtuar este issue, todavía sigo aprendiendo.
