### ISSUE TITLE
Corregir el nombre de la comunidad en el header

### ISSUE THREAD

**Issue by Addin** [coljs/medellinjs#274]
Hola, el nombre de la comunidad está mal escrito en el header, debería ser "MedellínJS" y dice "MEDELLIN JS".

<img width="519" alt="ver" src="https://user-images.githubusercontent.com/6179522/52894366-47ae0680-3176-11e9-85ae-bae4009bb902.PNG">

**Comment by josepplloo** [comment]
Hola @Addin Puedo tomar este Issue?

**Comment by Addin** [comment]
Sí, @josepplloo no hay problema.
