### ISSUE TITLE
Cerrar párrafo en la descripción de la comunidad

### ISSUE THREAD

**Issue by Addin** [coljs/medellinjs#275]
Hola, en la descripción de la comunidad falta cerrar un párrafo con el punto final.

<img width="523" alt="ver" src="https://user-images.githubusercontent.com/6179522/52894379-9196ec80-3176-11e9-91a2-5f6a837be86c.PNG">

**Comment by josepplloo** [comment]
Hola @Addin Tambien puedo tomar este Issue?

**Comment by Addin** [comment]
También puedes hacerlo @josepplloo, puedes colaborar en cualquier issue que desees.
