### ISSUE TITLE
Cerrar párrafo en la sección fundación

### ISSUE THREAD

**Issue by Addin** [coljs/medellinjs#277]
Hola, en la parte de "Documentos públicos" le falta el punto final al párrafo.

<img width="889" alt="ver" src="https://user-images.githubusercontent.com/6179522/52894467-c8213700-3177-11e9-912e-e70bf8a4f25a.PNG">

**Comment by erick2014** [comment]
this issue was merged in https://github.com/coljs/medellinjs/commit/bf5f32a7bfc645187915841501cdd5737b74f2dd
