### ISSUE TITLE
Cambio sección sponsors

### ISSUE THREAD

**Issue by Skouro** [coljs/medellinjs#287]
* Sería bueno que cuando se abra algún enlace de los sponsors sea en otra pestaña. 
*  Modificar la imagen de los sponsors de modo que no se pierda parte del logo.
![anotacion 2019-02-16 152600](https://user-images.githubusercontent.com/36453706/52904812-4543bf00-31ff-11e9-9c2e-9c8ea0743a25.jpg)

**Comment by erick2014** [comment]
Im going to work on this issue guys
