### ISSUE TITLE
Cambiar Medellin JS por MedellínJS en el Navbar y el Título en el sitio. 

### ISSUE THREAD

**Issue by josepplloo** [coljs/medellinjs#307]
# Error en sitio web
Typo en el nombre de la comunidad.
## Comportamiento esperado
Cambiar el texto `Medellin JS` por  `MedellínJS`.

## Comportamiento actual
![typo image](https://user-images.githubusercontent.com/1114740/56052136-4af8e500-5d16-11e9-97fd-f2ceef6927cb.png)
En esta zona escribe o adjunta una imagen de la salida actual que se observa del sitio web,
es preferible el uso de capturas de pantalla ademas de una descripción paso a paso de como reproducir el error.

## Pasos para reproducir el error

1. Abrir el navegador y entrar a la página de la [comunidad](https://medellinjs.org/)
2. Inspecionar el título y el navbar.

**Comment by JenyMzo** [comment]
No es un typo :) así definimos el nombre, sin tilde. @khriztianmoreno podemos cerrar este issue?

**Comment by khriztianmoreno** [comment]
Seguro que si.
