### ISSUE TITLE
Use a proper tool for auto deploy

### ISSUE THREAD

**Issue by julianduque** [coljs/medellinjs#40]
Current one is too hacky

**Comment by edsadr** [comment]
well ... I was checking this service ... https://codeship.com/ ... or do you have something in mind?

**Comment by julianduque** [comment]
Yes, I have something in mind, i'll give it a try and let you know ;)

**Comment by julianduque** [comment]
I'm thinking on ansible to a new Digital Ocean Machine

**Comment by c4milo** [comment]
I will let you build your own, but you will have to move over to Hooklift later on \o/

**Comment by edsadr** [comment]
Wohooooooooo ... I am just waiting for the first spin of your yoyo

**Comment by julianduque** [comment]
@c4milo for sure :+1:

**Comment by germanescobar** [comment]
What about [germanescobar/ukku](http://github.com/germanescobar/ukku) in the meantime?  :smile:

**Comment by julianduque** [comment]
@germanescobar will definitely take a look :)

**Comment by julianduque** [comment]
Main issue was fixed in https://github.com/coljs/medellinjs/commit/03670fb350e817c00866a87d51e7ede4ebb7acf5 cc @mixergtz 

Closing this and will reopen when we need a real and powerful deploy solution like `ukku` or a platform like `hooklift` ;) (we would love to be beta testers!)
