### ISSUE TITLE
Create a new page for sponsorship rules

### ISSUE THREAD

**Issue by edsadr** [coljs/medellinjs#41]
We should have the sponsorship page using the content of the hackpad

**Comment by julianduque** [comment]
+1

**Comment by julianduque** [comment]
@citrustaller (juli) tiene un par de ideas super buenas de como podemos ponerlo en un lenguaje mas bacano, le dire que las comparta por aqui

**Comment by edsadr** [comment]
Ok esperando a que @citrustaller nos colabore :smile:

**Comment by julianduque** [comment]
Podemos poner el texto plano en una pagina de patrocinios, hablemos mañana en Atom House :)

**Comment by julianduque** [comment]
Closed in favor of #51
