### ISSUE TITLE
Create a new page for speakers guidelines 

### ISSUE THREAD

**Issue by edsadr** [coljs/medellinjs#42]
we need to set an standard for our talks,  lets create a text so new speakers follow this in order to have better material and talks

**Comment by julianduque** [comment]
+1

**Comment by RamirezAlex** [comment]
:+1:

**Comment by davsket** [comment]
Nice!!!

**Comment by CodeMaxter** [comment]
I think is a good idea to have a slides.com account for Med.js, so we can have all meetup's slides in one place (in the standard, we could determinate to use slides.com like presentation choise)

**Comment by Addin** [comment]
Tal vez este issue se puede marcar como solucionado, no sé si lo que se presenta en la sección de "Inscribe tu charla" puedan ser los lineamientos que mencionan, tampoco sé si tienen la cuenta de slides.com a nombre de MedellinJS.

<img width="857" alt="capture" src="https://user-images.githubusercontent.com/6179522/52441805-aaa4fb00-2aef-11e9-9855-0f295ec92775.PNG">
