### ISSUE TITLE
Add missing JS communities in footer

### ISSUE THREAD

**Issue by julianduque** [coljs/medellinjs#50]

**Comment by edsadr** [comment]
Alvaro helps :P

**Comment by CodeMaxter** [comment]
Ayuda con qué?

--- Original Message ---

**Comment by julianduque** [comment]
@CodeMaxter en el footer sería bueno tener las otras comunidades JS: Popayán, Monteria y Manizales, no se cuales son las otras pero acá en el issue las podemos ir buscando.

**Comment by edsadr** [comment]
sorry @CodeMaxter .. got some time and got tired waiting for you to hep with the issue  :P .. solved here: https://github.com/coljs/medellinjs/pull/56
