### ISSUE TITLE
Add sponsors to website

### ISSUE THREAD

**Issue by julianduque** [coljs/medellinjs#51]
Current are:
- Ruta N (this needs to be the relevant one, bigger logo and stuff)
- Social Atom Ventures

**Comment by edsadr** [comment]
ok.. lets add them... but ... where?I would propose a new section, but we need the long awaited text for this one...

**Comment by edsadr** [comment]
Text is done already here: https://hackpad.com/Patrocinio-MedellinJS-s6pOl8quQsa

**Comment by julianduque** [comment]
@RamirezAlex compadre, este es el borrador de lo que habria en la página /aliados

La idea es tener un sitio, 3 columnas con los niveles de alianza y los logos de nuestros aliados por nivel y agradecimientos a los que nos han apoyado en el pasado.

El texto puede ser mejorado pero la idea es que saquemos esta sección lo mas pronto posible (a mas tardar la otra semana) por que ya empezamos a movernos en este aspecto este año y necesitamos las cosas claras.

Invito a @naranjitagolden para que nos ayude con los nombres de los niveles y con las ideas de mapeo de valor que ella tiene.
