### ISSUE TITLE
link chat is broken

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#53]
https://gitter.im/ColombiaJS/medellinjs return error 404.
![screenshot from 2015-02-17 08 59 40](https://cloud.githubusercontent.com/assets/1205255/6229240/6c46f94c-b683-11e4-81ba-99bf6b3696d7.png)

**Comment by julianduque** [comment]
PR welcome :)  new chat link is: https://gitter.im/coljs/medellinjs

**Comment by julianduque** [comment]
You can update this line and send us a pull request :D - https://github.com/coljs/medellinjs/blob/master/_harp/_header.ejs#L16

**Comment by julianduque** [comment]
Why closing, isn't fixed yet :)

**Comment by julianduque** [comment]
now it's on master!! closing this

**Comment by jessecogollo** [comment]
jajaj excellent. it was like real time!!! =)

**Comment by julianduque** [comment]
@jessecogollo when you push to master the website auto deploys and booom!
