### ISSUE TITLE
Reunión Organizadores - MedellinJS

### ISSUE THREAD

**Issue by julianduque** [coljs/medellinjs#59]
* @edsadr 
* @academo 
* @RamirezAlex 
* @CodeMaxter 
* @naranjitagolden

Invitar a Alexandra Vargas (no tengo su usuario de github)

## Temas a hablar

* Presente y Futuro MedellinJS
* Iniciativa para Mujeres
* NodeSchool International Day
* NodeBots International Day
* Otras iniciativas

## Lugar
* Citrico Living Lab - Santa Elena, Medellín
* Fecha y hora: Sábado 14 de Marzo, 11am (Vamos a hacer un almuercito bien rico)
* Pueden subir con su familia / pareja

Por favor confirmar si pueden asistir o si tienen otras propuestas de fecha y hora ojalá para este fin de semana (Marzo 7, 8)

Si alguien necesita direcciones para subir o un empujón en carro nos deja saber :)

**Comment by edsadr** [comment]
+1

**Comment by CodeMaxter** [comment]
+1, si necesitaría un empujón en carro

--- Original Message ---

**Comment by academo** [comment]
+2 voy con alexa :)

**Comment by julianduque** [comment]
@CodeMaxter podrias hablar con @edsadr que el va en carro para que quede mas fácil

**Comment by julianduque** [comment]
Propuesta: Que opinan si aplazamos la reunión para el próximo fin de semana (Marzo 14) a la misma hora y tambien me gustaria saber si @RamirezAlex confirma?

Si no pueden para esa fecha seguimos en pie para este Sábado.

**Comment by CodeMaxter** [comment]
Por mi está bien aplazar

--- Original Message ---

**Comment by RamirezAlex** [comment]
Puedo este sábado o puedo aplazar, cuando quieran. :)

**Comment by julianduque** [comment]
Que opinan @edsadr y @academo de aplazar?

**Comment by academo** [comment]
@julianduque por mi esta bien aplazarla o hacerla el Sabado

**Comment by RamirezAlex** [comment]
@edsadr aplazamos o para el sábado? @julianduque si Adrián dice que está bien aplazarla entonces quedaría aplazada, verdad?

**Comment by edsadr** [comment]
miercoles.. me perdi un dia y ya cambio todo.. no problem para el 14

**Comment by julianduque** [comment]
Aplazada para el 14 de Marzo entonces, la idea es tener un poco de tiempo para organizar un par de cosas que tenemos pendientes por aqui y asi hacer una reunion bien productiva y divertida :)

**Comment by julianduque** [comment]
Recuerden, la reunión es este sábado 14 de Marzo en Citrico (el ranchito en Santa Elena) - @RamirezAlex y @CodeMaxter cuadren con @edsadr para la subida.

Si alguien requiere instrucciones detalladas me preguntar por google hangout y por ahi le doy el telefono :)

**Comment by academo** [comment]
Creo que ya podemos cerrar este?
