### ISSUE TITLE
Event widget isn't loading

### ISSUE THREAD

**Issue by julianduque** [coljs/medellinjs#61]

**Comment by edsadr** [comment]
@academo was playing with this code yesterday :P

**Comment by julianduque** [comment]
@academo it's broken, fixing it now (reverting 4a798c679132a2c923048ae24ed018b53cbe2f0e)

**Comment by julianduque** [comment]
Fixed

**Comment by academo** [comment]
Yup totally my fault I thought we were going to replace that code with the calendar.

**Comment by julianduque** [comment]
@academo it's ok :) good we have `git rever`
