### ISSUE TITLE
crear nueva pagina medellinjs.org/sorteo

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#91]
Esta pagina debe ser capaz de mostrar un usuario de forma aleatoria, obteniendo los datos de la API de meetup.com (asistentes confirmados de un meetup seleccionado). El siguiente codigo puede ser de referencia http://codepen.io/edsadr/pen/EgkjZg

**Comment by camigomez35** [comment]
Hola :) yo quisiera colaborar con este issue, lo trabajaría este fin de semana 🙈

**Comment by camigomez35** [comment]
Tengo una duda con respecto a esta pagina.
Debería preguntar el id del meetup sobre el cual se desea hacer el sorteo o debería buscar el meetup activo y hacer el sorteo sobre ese? 😅 me hago entender?

**Comment by jessecogollo** [comment]
Hola @camigomez35  ambas opciones son validas... 
pueden ir las dos.
