### ISSUE TITLE
Agregar BucaramangaJS como comunidad

### ISSUE THREAD

**Issue by romelperez** [coljs/medellinjs#94]
Buenas!

Ya tenemos la comunidad BucaramangaJS para Bucaramanga y su área metropolitana.

https://twitter.com/bucaramangajs
http://bucaramangajs.org

Gracias

**Comment by jessecogollo** [comment]
Hola romel, super genial.
El proceso, si quieres que salga en la pagina de Medellinjs. Es que le hagas un fork a este repositorio, hagas los cambios pertinentes y envies el pull request. :+1:

**Comment by romelperez** [comment]
Listo @jessecogollo, gracias!
