### ISSUE TITLE
GOVERNANCE.md

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#98]
Crear el archivo GOVERNANCE.md en el repositorio de https://github.com/coljs/medellinjs y enviarlo como PR. Se puede basar en el de nodejs https://github.com/nodejs/node/blob/master/GOVERNANCE.md

**Comment by pablovem** [comment]
:raised_hand: Me gustaría colaborar con este issue.

**Comment by jessecogollo** [comment]
Ok @pablovem, muchas gracias por  postularte a esta tarea. Basicamente lo que debes hacer acá, es adaptar el `GOVERNANCE.md` para la nueva politica de medellinJS (español). Lo primero que debes es clonar este repositorio y crear el `GOVERNANCE.md en la raiz. Si quieres, podemos continuar esta conversación en colombia-dev para discutir el contenido que pudiera cambiar en elarchivo de medellinjs.

**Comment by pablovem** [comment]
Gracias @jessecogollo, sigamos entonces por `colombia-dev` para definir detalles.

**Comment by jessecogollo** [comment]
Se hizo merge, como una version alfa.
