### ISSUE TITLE
Comida

### ISSUE THREAD

**Issue by jessecogollo** [coljs/medellinjs#99]
La responsabilidad de esta tarea inicia desde el recibir la comida en el lugar del evento, hasta dejar completamente limpio el espacio asignado para servir.

- Pedir
- Recojer
- Organizar la comida el día del evento (servir, ordenar, esperar que todos coman, explicar las diferentes opciones de sabores)
- Inmediatamente iniciada la segunda charla o el receso para comer se debe recoger la mesa y dejar limpio todo el espacio habilitado para repartir la comida.
- Al finalizar el evento, disponer de los residuos en su lugar correspondiente.

**Tenga en cuenta que esta tarea requiere de un gran compromiso y es muy comun que no pueda asistir completamente a todo la charla,** *si no cree que pueda cumplir con esto, te invitamos a buscar otra tarea en la cual puedas ayudar*.

**Comment by mafesernaarboleda** [comment]
y tambien puedo ayudar con esta 👍

**Comment by JenyMzo** [comment]
Puedo ayudar acá. 😃

**Comment by jessecogollo** [comment]
@JenyMzo y @mafesernaarboleda  basicamente acá es estar pendiente para cuando lleguen las empanadas para ir a recogerlas, ubicarlas en la mesa y dejar todo listo para cuando terminen de comerquede todo limpio. normalmente si sobran empanadas y/o gaseosa se le regala a los vigilantes. tambien se guarda una empanada para el encargado de rutaN. Así que las espero el día del meetup. Y muchas gracias.

**Comment by JenyMzo** [comment]
Puedo ayudar con esto. @JenyMzo

**Comment by kathcode** [comment]
Yo también puedo ayudar aquí.

**Comment by edsadr** [comment]
Yo la pido y la recibo y la pongo en la mesa. necesito ayuda sriviendo gaseosa y limpiando, posiblemente me vaya antes de que termine :( ... @JenyMzo @kathcode  me ayudan? @mafesernaarboleda es speaker ahora...

**Comment by JenyMzo** [comment]
@edsadr de una 🙂

**Comment by JenyMzo** [comment]
Puedo ayudar acá... @JenyMzo

**Comment by pablovem** [comment]
✋

**Comment by Krank2me** [comment]
buenas tardes, yo puedo colaborar con esta tarea

**Comment by DaihanaMora** [comment]
Buenos dias, puedo ayudar con esto @DaihanaMora

**Comment by Krank2me** [comment]
buen día, yo colaboro con este issue

**Comment by edsadr** [comment]
Yo la pido y la ayuda que se requiere es cargarla y ponerla en la mesa tambien sirviendo gaseosa y limpiando, posiblemente me vaya antes de que termine :( ... @DaihanaMora @Krank2me  quedamos entonces así

**Comment by Krank2me** [comment]
Ok, no hay problema, muchas gracias

**Comment by maleja111** [comment]
Yo puedo ayudar en esta tarea

**Comment by Krank2me** [comment]
Yo también colaboro con esta tarea

**Comment by kathcode** [comment]
Yo puedo ayudar @kathcode :)

**Comment by maleja111** [comment]
yo puedo ayudar este 21 @maleja111

**Comment by Krank2me** [comment]
yo colaboro también

**Comment by Krank2me** [comment]
colaboro con la comida para el meetUp del 14 de marzo @krank2me
